blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Ishan96Dev/digital-portfolio-app/discussions
    about: Please ask and answer questions here. 