name: 🐛 Bug Report
description: Create a report to help us improve the Digital Portfolio App
title: "[BUG] "
labels: ["bug", "triage"]
assignees: ["Ishan96Dev"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us understand and fix the issue.

  - type: input
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      placeholder: e.g., UI/UX, Functionality, Performance, Theme-related
    validations:
      required: true

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: A clear and concise title for the bug
      placeholder: e.g., Theme switcher not working on mobile devices
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        Describe the bug in detail:
        - What happened?
        - What did you expect to happen?
        - How can we reproduce it?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: Describe what you expected to happen when following the steps above
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: Describe what actually happened when following the steps above
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Windows 10, macOS, Ubuntu]
        - Browser: [e.g., Chrome, Firefox, Safari]
        - Version: [e.g., 22]
        - Device: [e.g., Desktop, Mobile, Tablet]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots (if applicable)
        - Error messages
        - Console logs
        - Any other relevant information

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 